### PR TITLE
use datatables for player page win list

### PR DESCRIPTION
**Pull request by Kramin42**

### CODE REVIEW

**Comment by Kramin42** [comment]
[screenshot](https://cdn.discordapp.com/attachments/174032098166964224/234958518984245248/unknown.png)

**Comment by Kramin42** [comment]
[2:56 PM] chequers: ugh, that bottom line is so ugly
[2:56 PM] chequers: "showing 1 to 10 of 52 entries" :thumbsdown: dont need this at all
[2:56 PM] chequers: the pagination is also ugly, if it could be shrunk to first | prev | next | last that might be preferable
[2:57 PM] chequers: and don't let people customise number of rows
[2:57 PM] chequers: change 'search' to 'filter'
[2:57 PM] chequers: i agree that the higher contrast version is too high contrast
[2:58 PM] chequers: the page aesthetic is at least as important as the ability to distinguish rows easily
[2:58 PM] chequers: the high contrast version could work if the whole theme was revamped to be a sort of black & white newspaper style
[2:58 PM] chequers: otherwise, this look like a fantastic addition
[2:59 PM] chequers: the ability to filter games is really wonderful
[2:59 PM] chequers: longer term I'd like to improve the free text filtering as previously mentioned, and also adding some limited keywords like 'won' and so on, but that doesn't have to be in the initial version
[2:59 PM] chequers: actually, I would like a ? link next to the filter box which pops up a tooltip giving filter examples

**Comment by Kramin42** [comment]
image

**Comment by Kramin42** [comment]
image

**Comment by Kramin42** [comment]
image

**Comment by alexjurkiewicz** [comment]
Can you please update the PR to fix merge conflicts?

**Comment by Kramin42** [comment]
image

**Comment by Kramin42** [comment]
Done all requests except:
[2:59 PM] chequers: longer term I'd like to improve the free text filtering as previously mentioned, and also adding some limited keywords like 'won' and so on, but that doesn't have to be in the initial version
[2:59 PM] chequers: actually, I would like a ? link next to the filter box which pops up a tooltip giving filter examples

**Comment by alexjurkiewicz** [comment]
thanks for this! I'll try to get it to production soon :)

**Pull request merged**
